### ISSUE TITLE
NWN TOA Awakening Glitch

### ISSUE THREAD

**Issue by Eklutna** [jd28/the_awakening#6]
I am playing this wonderful mod for the first time in years, and I'm playing on my late-model OS X iMac with Steam.  I am finding numerous glitches, but they mostly work out.  However, having arrived at the Temple, my companions are not confined where Sindelaar and Azra will kill them:  the cages are completely empty.  When I come to the River, where I should find Montador, there is a campfire, but he is not there.  When I go to the market in the Hells where I should find my stuff and that of my companions, mine is there, but the boxes for my companions are completely empty. What gives?!  I realize I'm not likely to get an answer after all this time, but I live in hope.  Thanks.

**Comment by jd28** [comment]
Unfortunately, this was for an old PW so it's not the module you're looking
for information about.  Have you tried asking on the Neverwinter vault
forums?

**Comment by Eklutna** [comment]
Indeed I have.  It's such an old mod that I doubt that anyone is interested
any longer.
